- name: Check and determine OpenSSH vulnerability
  hosts: all
  gather_facts: no
  tasks:
    - name: Get SSH version
      command: ssh -V
      register: ssh_version_output
      ignore_errors: yes

    - name: Parse SSH version
      set_fact:
        ssh_version: "{{ ssh_version_output.stderr.split()[0].split('_')[1] if ssh_version_output.stderr else ssh_version_output.stdout.split()[0].split('_')[1] }}"
      when: ssh_version_output is defined

    - name: Determine vulnerability status
      set_fact:
        is_vulnerable: >
          {{
            (ssh_version is version('4.4p1', '<')) or
            (ssh_version is version('8.5p1', '>=') and ssh_version is version('9.8p1', '<'))
          }}
      when: ssh_version is defined

    - name: Display vulnerability status
      debug:
        msg: >
          SSH version {{ ssh_version }} on host {{ inventory_hostname }} is
          {{ 'vulnerable' if is_vulnerable else 'not vulnerable' }}.
      when: ssh_version is defined
